#!/bin/bash

BASE="/usr/share/asistente-actualizacion2/"
PASO_BASH="/usr/share/asistente-actualizacion/paso.conf"

UNO="/usr/share/asistente-actualizacion2/uno"
DOS="/usr/share/asistente-actualizacion2/dos"
PROGRESO="/usr/share/asistente-actualizacion2/progreso"
MSJPROGRESO="/usr/share/asistente-actualizacion2/msjprogreso"

. ${PASO}

# Determina el Disco Duro al cual instalar y actualizar el burg
PARTS=$/sbin/fdisk -l | awk '/^\/dev\// {if ($2 == "*") {if ($6 == "83") { print $1 };}}' | sed 's/+//g' )
DISCO=${parts:0:8}
RESULT=$echo ${DISCO} | sed -e 's/\//\\\//g')

for cadauno in $(cat $BASE/actualizar)
do
        todos=$todos" "$cadauno
done


sed -i "s/\/dev\/xxx/${RESULT}/g" ${DEBCONF_SEL}

while [ ${PASO} -lt 60 ]
do

[ $ps -A | grep -cw update-manager ) == 1 ] || [ $ps -A | grep -cw apt-get ) == 1 ] || [ $ps -A | grep -cw aptitude ) == 1 ] &&  zenity --title="Asistente de Actualización a Canaima 3.0" --text="¡Existe un gestor de paquetes trabajando! No podemos continuar." --error --width=600 && exit 1

. ${PASO}

case ${PASO} in

1)
zenity --title="Asistente de Actualización a Canaima 3.0" --text="Este asistente se encargará de hacer los cambios necesarios\npara actualizar el sistema a la versión 3.0 de Canaima.\n\nSe realizará la actualizacion de gran cantidad de paquetes\nLas aplicaciones que ud haya instalado en 2.X que requieran\nconfiguración durante la instalacion ameritaran de su intervención para ser configuradas, \nel resto de la actualización se realizará de forma transparente.\n\n\nSe recomienda conectar el equipo a una fuente de alimentación continua, al finalizar la actualizacion el sistema se reiniciará automaticamente, no apague el equipo hasta haber recibido el mensaje de \"Actualizacion Completada\".\nSe descargarán aprox: 1200MB.\n\n¿Desea continuar con la actualización?" --question --width=600
[ $? == 1 ] && exit 1
echo 'PASO=2' > ${PASO}
actualizador
;;

2)

echo $todos >> $BASE'predescargar'

#Pre descarga de todos los paquetes requeridos para la instalación
for paquete in $(cat $BASE'predescargar')
do
$contador=$[$contador+1]
aptitude install --download-only $paquete
echo "scale=3;$contador/1440*40" | bc > $BASE"progreso"
echo 'Descargando: $paquete' > $BASE"msjprogreso"

done

mkdir /usr/share/asistente-actualizacion2/predescargados
cp /var/cache/apt/archives/* /usr/share/asistente-actualizacion2/predescargados

echo "PASO=3" > $PASO_BASH
# ------- PREPARANDO CANAIMA 2.1 ------------------------------------------------------------------#
#==================================================================================================#

debconf-set-selections ${DEBCONF_SEL}

# Aseguramos que tenemos los repositorios correctos
cat <<EOF >/etc/apt/sources.list
#
# Repositorios de Canaima GNU/Linux
#

# Repositorio Antiguo
deb http://mirror/canaima3/repositorio/ aponwao usuarios

# Repositorio Estable
#deb http://mirror/canaima3/repositorio/ roraima usuarios

# Repositorio de Desarrollo
#deb http://mirror/canaima3/repositorio/ auyantepui usuarios

# Repositorio de la Base (Debian)
deb http://mirror/debian/ lenny main contrib non-free

EOF
echo
echo "PASO=3" > ${PASO}
;;

3)
# Actualizamos la lista de paquetes
aptitude update | tee /var/log/salida && sleep 2
echo "PASO=4" > ${PASO}
;;

4)
# Removemos paquetes huérfanos
apt-get autoclean | tee /var/log/salida && sleep 2
echo "PASO=5" > ${PASO}
;;

5)
# Actualizamos Canaima 2.1
DEBIAN_FRONTEND=noninteractive aptitude --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" full-upgrade | tee /var/log/salida && sleep 2
echo "PASO=6" > ${PASO}
;;

6)
# Instalamos otro proveedor de gnome-www-browser
DEBIAN_FRONTEND=noninteractive aptitude install --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" galeon | tee /var/log/salida && sleep 2
echo "PASO=7" > ${PASO}
;;

7)
# Removemos la configuración vieja del GRUB
rm /etc/default/grub && sleep 2
echo "PASO=8" > ${PASO}
;;

8)
# Limpiando Canaima 2.1 de aplicaciones no utilizadas en 3.0
DEBIAN_FRONTEND=noninteractive apt-get purge --force-yes -y openoffice* firefox* thunderbird* canaima-accesibilidad canaima-instalador-vivo canaima-particionador | tee /var/log/salida && sleep 2
echo "PASO=9" > ${PASO}
;;

9) 
# Limpiando paquetes huérfanos
DEBIAN_FRONTEND=noninteractive apt-get autoremove --force-yes -y | tee /var/log/salida && sleep 2
echo "PASO=10" > ${PASO}
;;

10) 
# ------- ACTUALIZANDO COMPONENTES DE INSTALACIÓN DE LA BASE (DEBIAN SQUEEZE) ---------------------#
#==================================================================================================#

# Estableciendo repositorios sólo para el sistema base
cat <<EOF >/etc/apt/sources.list
deb http://mirror/debian/ squeeze main contrib non-free

EOF

# Estableciendo prioridades superiores para paquetes provenientes de Debian
cat <<EOF >/etc/apt/preferences
Package: *
Pin: release o=Debian
Pin-Priority: 800

EOF

echo "PASO=11" > ${PASO}
;;

11) 
# Actualizamos la lista de paquetes
aptitude update | tee /var/log/salida && sleep 2
echo "PASO=12" > ${PASO}
;;

12) 
# Removemos paquetes huérfanos
apt-get autoclean | tee /var/log/salida && sleep 2
echo "PASO=13" > ${PASO}
;;

13) 
# Actualizando componentes fundamentales de instalación
DEBIAN_FRONTEND=noninteractive aptitude install --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" aptitude apt dpkg debian-keyring locales --without-recommends | tee /var/log/salida && sleep 2 
echo "PASO=14" > ${PASO}
;;

14) 
# Arreglando paquetes en mal estado
DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes -f install | tee /var/log/salida && sleep 2
echo "PASO=15" > ${PASO}
;;

15) 
# Instalando nuevo Kernel y librerías Perl
DEBIAN_FRONTEND=noninteractive aptitude install --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" linux-image-2.6.32-5-686 perl libperl5.10 | tee /var/log/salida && sleep 2
echo "PASO=16" > ${PASO}
;;

16) 
# Estableciendo repositorios sólo para el sistema base
debconf-set-selections ${DEBCONF_SEL}
cat <<EOF >/etc/apt/sources.list
deb http://mirror/debian/ squeeze main contrib non-free

EOF

# Estableciendo prioridades superiores para paquetes provenientes de Debian
cat <<EOF >/etc/apt/preferences
Package: *
Pin: release o=Debian
Pin-Priority: 800

EOF

echo "PASO=17" > ${PASO}
;;

17) 
# Actualizamos la lista de paquetes
aptitude update | tee /var/log/salida && sleep 2
echo "PASO=18" > ${PASO}
;;

18) 
# Removemos paquetes huérfanos
apt-get autoclean | tee /var/log/salida && sleep 2
echo "PASO=19" > ${PASO}
;;

19) 
# Arreglando paquetes en mal estado
DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes -f install | tee /var/log/salida && sleep 2
echo "PASO=20" > ${PASO}
;;

20) 
# Actualizando gestor de dispositivos UDEV
DEBIAN_FRONTEND=noninteractive aptitude install --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" udev | tee /var/log/salida && sleep 2
echo "PASO=21" > ${PASO}
;;

21) 
# Estableciendo repositorios sólo para el sistema base
debconf-set-selections ${DEBCONF_SEL}
cat <<EOF >/etc/apt/sources.list
deb http://mirror/debian/ squeeze main contrib non-free
EOF
echo "PASO=22" > ${PASO}
;;

22) 
# Estableciendo prioridades superiores para paquetes provenientes de Debian
cat <<EOF >/etc/apt/preferences
Package: *
Pin: release o=Debian
Pin-Priority: 800
EOF
echo "PASO=23" > ${PASO}
;;

23) 
# Actualizamos la lista de paquetes
aptitude update | tee /var/log/salida && sleep 2
echo "PASO=24" > ${PASO}
;;

24) 
# Removemos paquetes huérfanos
apt-get autoclean | tee /var/log/salida && sleep 2
echo "PASO=25" > ${PASO}
;;

25) 
# Arreglando paquetes en mal estado
DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes -f install | tee /var/log/salida && sleep 2
echo "PASO=26" > ${PASO}
;;

26) 
# Actualizando gconf2
DEBIAN_FRONTEND=noninteractive aptitude --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" install gconf2=2.28.1-6 libgconf2-4=2.28.1-6 gconf2-common=2.28.1-6 | tee /var/log/salida && sleep 2
echo "PASO=27" > ${PASO}
;;

27) 
# Actualización de componentes adicionales instalados por el usuario (no incluidos en canaima 2.1)

xterm -e "aptitude --assume-yes --allow-untrusted install $todos"

echo "PASO=28" > ${PASO}
;;

28) 
# Actualización parcial de la base
DEBIAN_FRONTEND=noninteractive apt-get --force-yes -y upgrade | tee /var/log/salida && sleep 2
echo "PASO=29" > ${PASO}
;;

29) 
# Actualización total de la base
DEBIAN_FRONTEND=noninteractive apt-get --force-yes -y dist-upgrade | tee /var/log/salida && sleep 2
echo "PASO=30" > ${PASO}
;;

30) 
# Actualización completa de la base
DEBIAN_FRONTEND=noninteractive aptitude --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" full-upgrade | tee /var/log/salida && sleep 2
echo "PASO=31" > ${PASO}
;;

31) 
# Estableciendo repositorios sólo para el sistema base
debconf-set-selections ${DEBCONF_SEL}
cat <<EOF >/etc/apt/sources.list
deb http://mirror/canaima3/repositorio/ roraima usuarios
deb http://mirror/debian/ squeeze main contrib non-free
EOF
echo "PASO=32" > ${PASO}
;;

32) 
# Estableciendo prioridades superiores para paquetes provenientes de Debian
cat <<EOF >/etc/apt/preferences
Package: *
Pin: release o=Canaima
Pin-Priority: 900

Package: *
Pin: release o=Debian
Pin-Priority: 800
EOF
echo "PASO=33" > ${PASO}
;;

33) 
# Actualizamos la lista de paquetes
aptitude update | tee /var/log/salida && sleep 2
echo "PASO=34" > ${PASO}
;;

34) 
# Removemos paquetes huérfanos
apt-get autoclean | tee /var/log/salida && sleep 2
echo "PASO=36" > ${PASO}
;;

36) 
# Arreglando paquetes en mal estado
DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes -f install | tee /var/log/salida && sleep 2
echo "PASO=37" > ${PASO}
;;

37) 
# Instalando llaves del repositorio Canaima
DEBIAN_FRONTEND=noninteractive aptitude install --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" canaima-llaves | tee /var/log/salida && sleep 2
echo "PASO=38" > ${PASO}
;;

38) 
# Removiendo paquetes innecesarios
DEBIAN_FRONTEND=noninteractive aptitude purge --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" epiphany-browser epiphany-browser-data libgraphviz4 libslab0 gtkhtml3.14 busybox-syslogd dsyslog inetutils-syslogd rsyslog socklog-run sysklogd syslog-ng libfam0c102 | tee /var/log/salida && sleep 2
echo "PASO=39" > ${PASO}
;;

39) 
# Removemos configuraciones obsoletas
rm -rf /etc/skel/.purple/ 
rm /etc/canaima_version 
rm /usr/share/applications/openoffice.org-*
echo "PASO=40" > ${PASO}
;;

40) 
# Instalando escritorio de Canaima 3.0
DEBIAN_FRONTEND=noninteractive aptitude install --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" canaima-escritorio-gnome | tee /var/log/salida && sleep 2
echo "PASO=41" > ${PASO}
;;

41) 
# Removiendo Navegador web de transición
DEBIAN_FRONTEND=noninteractive aptitude purge --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" galeon | tee /var/log/salida && sleep 2
echo "PASO=42" > ${PASO}
;;

42) 
# Actualización final a Canaima 3.0
DEBIAN_FRONTEND=noninteractive aptitude --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" full-upgrade | tee /var/log/salida && sleep 2
echo "PASO=43" > ${PASO}
;;

43) 
# Removiendo paquetes innecesarios
DEBIAN_FRONTEND=noninteractive aptitude purge --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" gstreamer0.10-gnomevfs splashy | tee /var/log/salida && sleep 2
echo "PASO=44" > ${PASO}
;;

44) 
# Actualizando a GDM3
DEBIAN_FRONTEND=noninteractive aptitude install --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" gdm3 | tee /var/log/salida && sleep 2
echo "PASO=46" > ${PASO}
;;

46) 
# Actualizando a BURG
DEBIAN_FRONTEND=noninteractive aptitude install --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" burg | tee /var/log/salida && sleep 2
echo "PASO=47" > ${PASO}
;;

47) 
# Reinstalando Base de Canaima
DEBIAN_FRONTEND=noninteractive aptitude reinstall --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" canaima-base | tee /var/log/salida && sleep 2
echo "PASO=48" > ${PASO}
;;

48) 
# Reinstalando Estilo Visual
DEBIAN_FRONTEND=noninteractive aptitude reinstall --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" canaima-estilo-visual | tee /var/log/salida && sleep 2
echo "PASO=49" > ${PASO}
;;

49) 
# Reinstalando Escritorio
DEBIAN_FRONTEND=noninteractive aptitude reinstall --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" canaima-escritorio-gnome | tee /var/log/salida && sleep 2
echo "PASO=50" > ${PASO}
;;

50) 
# Actualizando entradas del BURG
update-burg | tee /var/log/salida && sleep 2
echo "PASO=51" > ${PASO}
;;

51) 
# Estableciendo GDM3 como Manejador de Pantalla por defecto
echo "/usr/sbin/gdm3" > /etc/X11/default-display-manager && sleep 2
echo "PASO=52" > ${PASO}
;;

52) 
# Reconfigurando el Estilo Visual
dpkg-reconfigure canaima-estilo-visual | tee /var/log/salida && sleep 2
echo "PASO=53" > ${PASO}
;;

53) 
update-burg

		# Para cada usuario en /home/ ...
		for usuario in /home/*? ; do

			#Obteniendo sólo el nombre del usuario
			usuario_min=$(basename ${usuario})

			#Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
			case  $(grep "${usuario_min}:.*:.*:.*:.*:.*:::" /etc/shadow) in

				'')
				#No hace nada si no se encuentra en /etc/shadow
				;;

				*)

					# Elimina configuracion de gconf previo
					rm -rf ${usuario}/.gconf/
				;;
			esac

		done


echo 'PASO=70' > ${PASO}
reboot
exit 0
;;
esac
done
