#!/bin/bash

BASE="/usr/share/asistente-actualizacion/"
PASO_BASH="/usr/share/asistente-actualizacion/paso.conf"

. ${PASO_BASH}

##Determina el Disco Duro al cual instalar y actualizar el burg
parts=$(/sbin/fdisk -l | awk '/^\/dev\// {if ($2 == "*") {if ($6 == "83") { print $1 };}}' |sed s/+//g )
text_orig=/dev/c
disco=${parts:0:8}
result=$(echo $disco | sed -e 's/\//\\\//g')
echo $result

echo 'sed -i "s/\/dev\/xxx/$result/g" $BASE/selections.conf'
sed -i "s/\/dev\/xxx/$result/g" $BASE/selections.conf

 
while [ ${PASO} -lt 60 ]
do

. ${PASO_BASH}
case ${PASO} in

1)
zenity --title="Asistente de Actualización a Canaima 3.0" --text="Este asistente se encargará de hacer los cambios necesarios\npara actualizar el sistema a la versión 3.0 de Canaima.\n\nSe realizará la actualizacion de gran cantidad de paquetes\nLas aplicaciones que ud haya instalado en 2.X que requieran\nconfiguración durante la instalacion ameritaran de su intervención para ser configuradas, \nel resto de la actualización se realizará de forma transparente.\n\n\nSe recomienda conectar el equipo a una fuente de alimentación continua, y no apagar el equipo hasta haber recibido el mensaje de \"Actualizacion Completada\".\n\n¿Desea continuar con la actualización?" --question --width=600
echo 'PASO=2' > ${PASO_BASH}
asistente-actualizacion
;;

2)

# ------- PREPARANDO CANAIMA 2.1 ------------------------------------------------------------------#
#==================================================================================================#

debconf-set-selections $BASE"selections.conf"

# Aseguramos que tenemos los repositorios correctos
cat <<EOF >/etc/apt/sources.list
#
# Repositorios de Canaima GNU/Linux
#

# Repositorio Antiguo
deb http://mirror/canaima3/repositorio/ aponwao usuarios

# Repositorio Estable
#deb http://mirror/canaima3/repositorio/ roraima usuarios

# Repositorio de Desarrollo
#deb http://mirror/canaima3/repositorio/ auyantepui usuarios

# Repositorio de la Base (Debian)
deb http://mirror/debian/ lenny main contrib non-free


EOF

echo "PASO=3" > $PASOBASH
;;
3)
# Actualizamos la lista de paquetes
( aptitude update >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Actualizando lista de paquetes ..." --progress --pulsate --auto-close --width=600
echo "PASO=4" > $PASOBASH

;;
4)
# Removemos paquetes huérfanos
( apt-get autoclean >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Removiendo paquetes huérfanos ..." --progress --pulsate --auto-close --width=600
echo "PASO=5" > $PASOBASH

;;
5)
# Actualizamos Canaima 2.1
( DEBIAN_FRONTEND=noninteractive aptitude --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" full-upgrade >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Actualizando Canaima 2.1 ..." --progress --pulsate --auto-close --width=600
echo "PASO=6" > $PASOBASH

;;
6)
# Instalamos otro proveedor de gnome-www-browser
( DEBIAN_FRONTEND=noninteractive aptitude install --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" galeon >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Preparando migración de Firefox a Cunaguaro ..." --progress --pulsate --auto-close --width=600
echo "PASO=7" > $PASOBASH

;;
7)
# Removemos la configuración vieja del GRUB
( rm /etc/default/grub &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Preparando migración de Firefox a Cunaguaro ..." --progress --pulsate --auto-close --width=600
echo "PASO=8" > $PASOBASH

;;
8)
# Limpiando Canaima 2.1 de aplicaciones no utilizadas en 3.0
( DEBIAN_FRONTEND=noninteractive apt-get purge --force-yes -y openoffice* firefox* thunderbird* canaima-accesibilidad canaima-instalador-vivo canaima-particionador >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Limpiando Canaima 2.1 de aplicaciones no utilizadas en 3.0 ..." --progress --pulsate --auto-close --width=600
echo "PASO=9" > $PASOBASH

;;
9) 
# Limpiando paquetes huérfanos
( DEBIAN_FRONTEND=noninteractive apt-get autoremove --force-yes -y >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Removiendo paquetes huérfanos ..." --progress --pulsate --auto-close --width=600
echo "PASO=10" > $PASOBASH


;;
10) 
# ------- ACTUALIZANDO COMPONENTES DE INSTALACIÓN DE LA BASE (DEBIAN SQUEEZE) ---------------------#
#==================================================================================================#

# Estableciendo repositorios sólo para el sistema base
cat <<EOF >/etc/apt/sources.list
deb http://mirror/debian/ squeeze main contrib non-free

EOF

# Estableciendo prioridades superiores para paquetes provenientes de Debian
cat <<EOF >/etc/apt/preferences
Package: *
Pin: release o=Debian
Pin-Priority: 800

EOF

echo "PASO=11" > $PASOBASH

;;
11) 
# Actualizamos la lista de paquetes
( aptitude update >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Actualizando lista de paquetes ..." --progress --pulsate --auto-close --width=600
echo "PASO=12" > $PASOBASH

;;
12) 
# Removemos paquetes huérfanos
( apt-get autoclean >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Removiendo paquetes huérfanos ..." --progress --pulsate --auto-close --width=600
echo "PASO=13" > $PASOBASH

;;
13) 
# Actualizando componentes fundamentales de instalación
( DEBIAN_FRONTEND=noninteractive aptitude install --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" aptitude apt dpkg debian-keyring locales --without-recommends >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Actualizando componentes fundamentales de instalación ..." --progress --pulsate --auto-close --width=600
echo "PASO=14" > $PASOBASH

;;
14) 
# Arreglando paquetes en mal estado
( DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes -f install >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Arreglando paquetes en mal estado ..." --progress --pulsate --auto-close --width=600
echo "PASO=15" > $PASOBASH

;;
15) 
# Instalando nuevo Kernel y librerías Perl
( DEBIAN_FRONTEND=noninteractive aptitude install --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" linux-image-2.6.32-5-686 perl libperl5.10 >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Instalando nuevo Kernel y librerías Perl ..." --progress --pulsate --auto-close --width=600
echo "PASO=16" > $PASOBASH


;;
16) 
dhclient
# Estableciendo repositorios sólo para el sistema base

debconf-set-selections $BASE"selections.conf"
cat <<EOF >/etc/apt/sources.list
deb http://mirror/debian/ squeeze main contrib non-free

EOF

# Estableciendo prioridades superiores para paquetes provenientes de Debian
cat <<EOF >/etc/apt/preferences
Package: *
Pin: release o=Debian
Pin-Priority: 800

EOF

echo "PASO=17" > $PASOBASH
;;
17) 
# Actualizamos la lista de paquetes
( aptitude update >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Actualizando lista de paquetes ..." --progress --pulsate --auto-close --width=600


echo "PASO=18" > $PASOBASH
;;
18) 
# Removemos paquetes huérfanos
( apt-get autoclean >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Removiendo paquetes huérfanos ..." --progress --pulsate --auto-close --width=600

echo "PASO=19" > $PASOBASH

;;
19) 
# Arreglando paquetes en mal estado
( DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes -f install >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Arreglando paquetes en mal estado ..." --progress --pulsate --auto-close --width=600


echo "PASO=20" > $PASOBASH
;;
20) 
# Actualizando gestor de dispositivos UDEV
( DEBIAN_FRONTEND=noninteractive aptitude install --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" udev >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Actualizando gestor de dispositivos UDEV ..." --progress --pulsate --auto-close --width=600



echo "PASO=21" > $PASOBASH
;;
21) 
# Estableciendo repositorios sólo para el sistema base

debconf-set-selections $BASE"selections.conf"
cat <<EOF >/etc/apt/sources.list
deb http://mirror/debian/ squeeze main contrib non-free

EOF

echo "PASO=22" > $PASOBASH
;;
22) 
# Estableciendo prioridades superiores para paquetes provenientes de Debian
cat <<EOF >/etc/apt/preferences
Package: *
Pin: release o=Debian
Pin-Priority: 800

EOF

echo "PASO=23" > $PASOBASH
;;
23) 
dhclient

# Actualizamos la lista de paquetes
( aptitude update >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Actualizando lista de paquetes ..." --progress --pulsate --auto-close --width=600

echo "PASO=24" > $PASOBASH
;;
24) 
# Removemos paquetes huérfanos
( apt-get autoclean >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Removiendo paquetes huérfanos ..." --progress --pulsate --auto-close --width=600

echo "PASO=25" > $PASOBASH
;;
25) 
# Arreglando paquetes en mal estado
( DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes -f install >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Arreglando paquetes en mal estado ..." --progress --pulsate --auto-close --width=600

echo "PASO=26" > $PASOBASH
;;
26) 
# Actualizando gconf2
( DEBIAN_FRONTEND=noninteractive aptitude --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" install gconf2=2.28.1-6 libgconf2-4=2.28.1-6 gconf2-common=2.28.1-6 >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Actualizando gconf2 ..." --progress --pulsate --auto-close --width=600

echo "PASO=27" > $PASOBASH
;;
27) 
# Actualización de componentes adicionales instalados por el usuario (no incluidos en canaima 2.1)

dpkg-query -W -f='${Package}\t${Status}\n' | grep "install ok installed" | awk '{ print $1 }' > $BASE/este

diff $BASE/21 $BASE/este | grep ">" | awk '{ print $2 }' > $BASE/actualizar
for cadauno in $(cat $BASE/actualizar)
do
        todos=$todos" "$cadauno
done
gnome-terminal --command="aptitude --assume-yes --allow-untrusted install $todos"

echo "PASO=28" > $PASOBASH
;;
28) 
# Actualización parcial de la base
( DEBIAN_FRONTEND=noninteractive apt-get --force-yes -y upgrade >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Actualización parcial de la base ..." --progress --pulsate --auto-close --width=600

echo "PASO=29" > $PASOBASH
;;
29) 
# Actualización total de la base
( DEBIAN_FRONTEND=noninteractive apt-get --force-yes -y dist-upgrade >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Actualización total de la base ..." --progress --pulsate --auto-close --width=600

echo "PASO=30" > $PASOBASH
;;
30) 
# Actualización completa de la base
( DEBIAN_FRONTEND=noninteractive aptitude --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" full-upgrade >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Actualización completa de la base ..." --progress --pulsate --auto-close --width=600

echo "PASO=31" > $PASOBASH
;;
31) 
# Estableciendo repositorios sólo para el sistema base

debconf-set-selections $BASE"selections.conf"
cat <<EOF >/etc/apt/sources.list
deb http://mirror/canaima3/repositorio/ roraima usuarios
deb http://mirror/debian/ squeeze main contrib non-free

EOF

echo "PASO=32" > $PASOBASH
;;
32) 
# Estableciendo prioridades superiores para paquetes provenientes de Debian
cat <<EOF >/etc/apt/preferences
Package: *
Pin: release o=Canaima
Pin-Priority: 900

Package: *
Pin: release o=Debian
Pin-Priority: 800

EOF

echo "PASO=33" > $PASOBASH
;;
33) 
# Actualizamos la lista de paquetes
( aptitude update >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Actualizando lista de paquetes ..." --progress --pulsate --auto-close --width=600

echo "PASO=34" > $PASOBASH
;;
34) 
# Removemos paquetes huérfanos
( apt-get autoclean >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Removiendo paquetes huérfanos ..." --progress --pulsate --auto-close --width=600

echo "PASO=36" > $PASOBASH
;;
36) 
# Arreglando paquetes en mal estado
( DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes -f install >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Arreglando paquetes en mal estado ..." --progress --pulsate --auto-close --width=600

echo "PASO=37" > $PASOBASH
;;
37) 
# Instalando llaves del repositorio Canaima
( DEBIAN_FRONTEND=noninteractive aptitude install --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" canaima-llaves >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Instalando llaves del repositorio Canaima ..." --progress --pulsate --auto-close --width=600

echo "PASO=38" > $PASOBASH
;;
38) 
# Removiendo paquetes innecesarios
( DEBIAN_FRONTEND=noninteractive aptitude purge --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" epiphany-browser epiphany-browser-data libgraphviz4 libslab0 gtkhtml3.14 busybox-syslogd dsyslog inetutils-syslogd rsyslog socklog-run sysklogd syslog-ng libfam0c102 >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Removiendo paquetes innecesarios ..." --progress --pulsate --auto-close --width=600

echo "PASO=39" > $PASOBASH
;;
39) 
# Removemos configuraciones obsoletas
rm -rf /etc/skel/.purple/ 
rm /etc/canaima_version 
rm /usr/share/applications/openoffice.org-*

echo "PASO=40" > $PASOBASH
;;
40) 
# Instalando escritorio de Canaima 3.0
( DEBIAN_FRONTEND=noninteractive aptitude install --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" canaima-escritorio-gnome >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Instalando escritorio de Canaima 3.0 ..." --progress --pulsate --auto-close --width=600

echo "PASO=41" > $PASOBASH
;;
41) 
# Removiendo Navegador web de transición
( DEBIAN_FRONTEND=noninteractive aptitude purge --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" galeon >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Removiendo Navegador web de transición ..." --progress --pulsate --auto-close --width=600

;;
echo "PASO=42" > $PASOBASH
42) 
# Actualización final a Canaima 3.0
( DEBIAN_FRONTEND=noninteractive aptitude --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" full-upgrade >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Actualización final a Canaima 3.0 ..." --progress --pulsate --auto-close --width=600

echo "PASO=43" > $PASOBASH
;;
43) 
# Removiendo paquetes innecesarios
( DEBIAN_FRONTEND=noninteractive aptitude purge --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" gstreamer0.10-gnomevfs splashy >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Removiendo paquetes innecesarios ..." --progress --pulsate --auto-close --width=600

echo "PASO=45" > $PASOBASH
;;
44) 
# Actualizando a GDM3
( DEBIAN_FRONTEND=noninteractive aptitude install --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" gdm3 >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Actualizando a GDM3 ..." --progress --pulsate --auto-close --width=600

echo "PASO=46" > $PASOBASH
;;
46) 
# Actualizando a BURG
( DEBIAN_FRONTEND=noninteractive aptitude install --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" burg >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Actualizando a BURG ..." --progress --pulsate --auto-close --width=600

echo "PASO=47" > $PASOBASH
;;
47) 
# Reinstalando Base de Canaima
( DEBIAN_FRONTEND=noninteractive aptitude reinstall --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" canaima-base >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Reinstalando Base de Canaima ..." --progress --pulsate --auto-close --width=600

echo "PASO=48" > $PASOBASH
;;
48) 
# Reinstalando Estilo Visual
( DEBIAN_FRONTEND=noninteractive aptitude reinstall --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" canaima-estilo-visual >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Reinstalando Estilo Visual ..." --progress --pulsate --auto-close --width=600

echo "PASO=49" > $PASOBASH
;;
49) 
# Reinstalando Escritorio
( DEBIAN_FRONTEND=noninteractive aptitude reinstall --assume-yes --allow-untrusted -o DPkg::Options::="--force-confmiss" canaima-escritorio-gnome >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Reinstalando Escritorio ..." --progress --pulsate --auto-close --width=600

#Eliminando kernels anteriores
for KERNEL in $( dpkg-query -W -f='${Package} ${Version}\t${Status}\n' linux-image* linux-headers* linux-source* linux-kbuild* | grep "install ok installed" | awk '{ print $1"_____"$2 }'); do
KERNEL_PAQUETE=$( echo ${KERNEL} | sed 's/_____.*//g' )
KERNEL_VERSION=${KERNEL#${KERNEL_PAQUETE}"_____"}
[ $( echo ${KERNEL_VERSION} | awk -F . '{print $3}' | sed 's/-.*//g' | sed 's/+.*//g' ) -lt 32 ] && PARA_DESINSTALAR=${PARA_DESINSTALAR}" "${KERNEL_PAQUETE}
done

aptitude purge ${PARA_DESINSTALAR}

echo "PASO=50" > $PASOBASH
;;
50) 
# Actualizando entradas del BURG
( update-burg >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Actualizando entradas del BURG ..." --progress --pulsate --auto-close --width=600

echo "PASO=51" > $PASOBASH
;;
51) 
# Estableciendo GDM3 como Manejador de Pantalla por defecto
( echo "/usr/sbin/gdm3" > /etc/X11/default-display-manager &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Estableciendo GDM3 como Manejador de Pantalla por defecto ..." --progress --pulsate --auto-close --width=600

echo "PASO=52" > $PASOBASH
;;
52) 
# Reconfigurando el Estilo Visual
( dpkg-reconfigure canaima-estilo-visual >> /var/log/salida   &&  sleep 2  ) | zenity --title="Asistente de Actualización a Canaima 3.0" --text="Reconfigurando el Estilo Visual ..." --progress --pulsate --auto-close --width=600

echo "PASO=53" > $PASOBASH
;;
53) 
update-burg

		# Para cada usuario en /home/ ...
		for usuario in /home/*? ; do

			#Obteniendo sólo el nombre del usuario
			usuario_min=$(basename ${usuario})

			#Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
			case  $(grep "${usuario_min}:.*:.*:.*:.*:.*:::" /etc/shadow) in

				'')
				#No hace nada si no se encuentra en /etc/shadow
				;;

				*)

					# Elimina configuracion de gconf previo
					rm -rf ${usuario}/.gconf/
				;;
			esac

		done


echo 'PASO=60' > ${PASO_BASH}
$BASEfinasist
echo "Reinicie el Sistema"

;;
esac
done
